FROM circleci/python:3 as builder

CMD ["python", "/app/specgen/generate_vocabulary.py", "--help"]
VOLUME /data

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN sudo pip install --no-cache-dir -r requirements.txt

COPY templates/ /app/templates
COPY specgen/ /app/specgen
