FROM circleci/node:14.16.1-buster

#RUN useradd -m circleci
USER circleci

RUN sudo apt-get install vim

WORKDIR /app
ADD . /app
#RUN sudo npm set unsafe-perm true
RUN sudo npm install
RUN sudo npm install eslint
