FROM cimg/node:20.15

#RUN useradd -m circleci
USER circleci

RUN sudo apt-get install vim

WORKDIR /app
ADD . /app
#RUN sudo npm set unsafe-perm true
RUN sudo npm install
RUN sudo npm install eslint

#RUN sudo npm install --global @oslo-flanders/ea-converter

